safe: false # A hack as environment variable (https://github.com/plusjade/jekyll-bootstrap/issues/84)
auto: true
server: true
permalink: none
pygments: true
markdown: redcarpet


exclude: [ "Gruntfile.coffee" ]
redcarpet:
  extensions: [ "tables", "with_toc_data" ]
