safe: false # A hack as environment variable (https://github.com/plusjade/jekyll-bootstrap/issues/84)
permalink: none
pygments: true
markdown: redcarpet

exclude: [ "Gruntfile.coffee", "node_modules", "CNAME", "package.json", "js/components" ]
redcarpet:
  extensions: [ "tables", "with_toc_data" ]
